ci/script: allow retries
So far, most if not all failures have been temporary network issues.

diff --git a/ci/script b/ci/script
--- a/ci/script
+++ b/ci/script
@@ -28,17 +28,38 @@ EOF
 
 image="snh48live/kvm48:master-python-$PYTHON_VERSION"
 
-sudo docker run -it --rm -v "$PWD/data:/data" "$image" --debug --config data/kvm48-config.yml
+test_run() {
+    blue=$'\e[34m'
+    yellow=$'\e[33m'
+    red=$'\e[31m'
+    reset=$'\e[0m'
+    for try in {1..3}; do
+        echo -E "${blue}> kvm48 $@${reset}" >&2
+        sudo docker run -it --rm -v "$PWD/data:/data" "$image" "$@" || {
+            if [[ $try != 3 ]]; then
+                echo -E "${yellow}kvm48 $@ failed but it may be a temporary network issue; retrying in 30 seconds...${reset}" >&2
+                sleep 30
+                continue
+            else
+                echo -E "${red}kvm48 $@ failed after 3 tries${reset}" >&2
+                exit 1
+            fi
+        }
+        break
+    done
+}
+
+test_run --debug --config data/kvm48-config.yml
 sudo rm -f data/*/*.mp4
 
 # Test a known date range with both mp4 and m3u8 URLs to download.
-sudo docker run -it --rm -v "$PWD/data:/data" "$image" --debug --config data/kvm48-config.yml --from 2018-10-25 --to 2018-10-27
+test_run --debug --config data/kvm48-config.yml --from 2018-10-25 --to 2018-10-27
 sudo rm -f data/*/*.mp4
 
-sudo docker run -it --rm -v "$PWD/data:/data" "$image" --debug --config data/kvm48-config.yml --mode perf --dry
+test_run --debug --config data/kvm48-config.yml --mode perf --dry
 
 # 2018-06-09 is a day with a short VOD: 其它/20180609 “砥砺前行” SNH48 GROUP 第五届偶像年度人气总决选启动仪式 第五届总选启动仪式.mp4
-sudo docker run -it --rm -v "$PWD/data:/data" "$image" --debug --config data/kvm48-config.yml --mode perf --from 2018-06-09 --to 2018-06-09
+test_run --debug --config data/kvm48-config.yml --mode perf --from 2018-06-09 --to 2018-06-09
 
 rm data/kvm48-config.yml
 ls -lh data
